/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Deployment of Angular CLI applications to a remote FTP server
 */
export interface DeployOptions {
  /**
   * This is an example how to override the workspace set of options. --- Base url for the application being built. Same as `ng build --base-href=/XXX/`.
   */
  baseHref?: string;
  /**
   * A named build target, as specified in the `configurations` section of angular.json. Each named target is accompanied by a configuration of option defaults for that target. This is equivalent to calling the command `ng build --configuration=XXX`.
   */
  configuration?: string;
  /**
   * Skip build process during deployment.
   */
  noBuild?: boolean;
  /**
   * Host to connect to
   */
  host?: string;
  /**
   * Host port to connect to
   */
  port?: number;
  /**
   * Use TLS for connection
   */
  tls?: boolean;
  /**
   * Username to login
   */
  username?: string;
  /**
   * Password to login
   */
  password?: string;
  /**
   * Remote directory path to deploy to
   */
  remoteDir?: string;
  /**
   * Flag if the remote directory should be emptied before deployment
   */
  cleanRemote?: boolean;
  /**
   * Extend log output (using --dry-Run will set --verbose to true)
   */
  verbose?: boolean;
  /**
   * For testing: Run through without making any changes. Execute with --dry-run and nothing will happen.
   */
  dryRun?: boolean;
  [k: string]: unknown;
}
